# Generated by Django 6.0.7 on 2026-07-22 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super', '0002_apartment_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
